#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend calebdev.tech
        bind 0:80
        default_backend nodes

backend nodes
        balance roundrobin
        server web-01 100.25.148.159:80
        server web-02 100.25.157.62:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
