#!/usr/bin/env bash
# A script that stops 4-to_infinity_and_beyond process
./4-to_infinity_and_beyond &
bg_process_pid=$!
read -p "Press Enter to stop the process"
kill "$bg_process_pid"
echo "Terminated"
