#!/usr/bin/env bash
# A script displays To infinity and beyond indefinitely with a sleep 2 in between
while true; do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
