#!/usr/bin/env bash
#Script that loops from 1 to 10 displays"bad luck" for the 4th iteration and "good luck" for the 8th iteration.
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo -e "bad luck"
	elif [ $count -eq 8 ]; then
		echo -e "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
