#!/usr/bin/env bash
#Script that displays the content of the current directory in a list format
# Only display the part of the name after the first dash

for file in *; do
	if [[ ! $file =~ ^\..* ]]; then
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done
