#!/usr/bin/env bash

# Script to provide information about the school file

file_path="school.txt"

if [ -e "$file_path" ]; then
    echo "school file exists"
    
    if [ -s "$file_path" ]; then
        echo "school file is not empty"

        if [ -f "$file_path" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
