#!/usr/bin/env bash
# sudo wget -O mysql57 https://raw.githubusercontent.com/nuuxcode/alx-system_engineering-devops/master/scripts/mysql57 && sudo chmod +x mysql57 && sudo ./mysql57
echo ""
echo "if wanna read the guide:"
echo "https://docs.google.com/document/d/1btVRofXP75Cj90_xq2x8AmzuMPOKq6D_Dt_SCDD6GrU/"
echo ""
echo ""
echo "-------------------------------"
echo "# Remove Existing MySQL Versions"
echo "-------------------------------"
echo ""
sudo apt-get remove --purge mysql-server mysql-client mysql-common -y && sudo apt-get autoremove -y
echo ""

echo "-------------------------------"
echo "# Remove MySQL Apt Configuration"
echo "-------------------------------"
echo ""
sudo rm -rf /etc/apt/sources.list.d/mysql.list*
sudo rm -rf /var/lib/mysql-apt-config
sudo dpkg --purge mysql-apt-config

echo ""
echo "-------------------------------"
echo "# Remove MySQL Configuration Files"
echo "-------------------------------"
echo ""
sudo rm -rf /etc/mysql /var/lib/mysql
echo "Done!"

echo ""
echo "-------------------------------"
echo "# Update Packages"
echo "-------------------------------"
echo ""
sudo apt update

echo ""
echo "-------------------------------"
echo "# Clean APT Cache"
echo "-------------------------------"
echo ""
sudo apt clean
echo "Done!"

echo ""
echo "-------------------------------"
echo "# Configure Any Pending Packages"
echo "-------------------------------"
echo ""
sudo dpkg --configure -a
echo "Done!"
